# Generated by Django 3.1 on 2020-09-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200925_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field=300, upload_to='listing_pics', width_field=300),
        ),
    ]
