# Generated by Django 3.1 on 2020-09-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-creation_date',)},
        ),
    ]
