# Generated by Django 3.1 on 2020-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200926_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
