# Generated by Django 3.1 on 2020-09-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200926_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wishlist', to='auctions.listing'),
        ),
    ]
