# Generated by Django 3.1 on 2020-09-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_user_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing',
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlist', to='auctions.Listing'),
        ),
    ]
