# Generated by Django 3.1 on 2020-09-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='listings',
        ),
    ]
