# Generated by Django 3.1 on 2020-09-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200927_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-creation_date',)},
        ),
    ]
